server:
  port: 9000

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: 1q2w3e
    platform: postgres
    url: jdbc:postgresql://localhost:5432/happy_pet
    username: postgres
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false
    javax:
      persistence:
        validation:
          mode: none
    show-sql: true

logging:
  file: happy_pet.log
  level:
      com:
        epam:
          sdet: ERROR
        org:
          springframework: ERROR